/**
 * Verification against the Swiss Ephemeris.
 *
 * tests/golden.json is generated by tools/golden.py from pyswisseph with SIDM_LAHIRI — 1,975 sample
 * dates spanning 1900–2100 plus hourly Moon positions across four whole days. The thresholds below
 * are the MEASURED accuracy of this engine with a little headroom, not aspirational numbers: if a
 * change makes any body worse, this fails.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  chartAt, siderealLongitude, ayanamsaDeg, julianDay, fromJulianDay, parseDate, angleDiff,
  type Body,
} from "../src/engine/ephemeris";

type Golden = {
  rows: { jd: number; date: string; ayanamsa: number; b: Record<string, [number, number]> }[];
  moon_days: { date: string; hourly: number[] }[];
};

const golden: Golden = JSON.parse(
  readFileSync(fileURLToPath(new URL("./golden.json", import.meta.url)), "utf8"),
);

/** Maximum longitude error tolerated, in ARCMINUTES. */
const TOLERANCE: Record<Body, number> = {
  Sun: 1.5, Moon: 2.5, Mercury: 2, Venus: 2, Mars: 4,
  Jupiter: 13, Saturn: 26, Uranus: 5, Neptune: 3, Pluto: 3,
};

describe("sidereal ephemeris vs Swiss Ephemeris", () => {
  it("has golden data to check against", () => {
    expect(golden.rows.length).toBeGreaterThan(1900);
  });

  it("reproduces the Lahiri ayanamsa essentially exactly", () => {
    let worst = 0;
    for (const row of golden.rows) {
      worst = Math.max(worst, Math.abs(ayanamsaDeg((row.jd - 2451545.0) / 36525) - row.ayanamsa));
    }
    expect(worst).toBeLessThan(1e-5);
  });

  it("places every body within tolerance across 1900–2100", () => {
    const worst: Partial<Record<Body, number>> = {};
    for (const row of golden.rows) {
      const chart = chartAt(row.jd);
      for (const p of chart.placements) {
        const truth = row.b[p.body];
        if (!truth) continue;
        const err = Math.abs(angleDiff(p.lon, truth[0])) * 60; // arcminutes
        if (err > (worst[p.body] ?? 0)) worst[p.body] = err;
      }
    }
    for (const [body, limit] of Object.entries(TOLERANCE) as [Body, number][]) {
      expect.soft(worst[body], `${body} max error ${worst[body]?.toFixed(2)}′`).toBeLessThan(limit);
    }
  });

  it("gets the direction of motion right, including retrogrades", () => {
    let checked = 0, wrong = 0;
    for (const row of golden.rows) {
      const chart = chartAt(row.jd);
      for (const p of chart.placements) {
        const truth = row.b[p.body];
        if (!truth) continue;
        const trueSpeed = truth[1];
        // Skip stations: within 0.02°/day of zero the sign is genuinely ambiguous at our accuracy.
        if (Math.abs(trueSpeed) < 0.02) continue;
        checked++;
        if (Math.sign(p.speed) !== Math.sign(trueSpeed)) wrong++;
      }
    }
    expect(checked).toBeGreaterThan(10000);
    expect(wrong).toBe(0);
  });

  it("tracks the Moon hour by hour across whole days", () => {
    for (const day of golden.moon_days) {
      const p = parseDate(day.date)!;
      day.hourly.forEach((truth, hour) => {
        const lon = siderealLongitude("Moon", julianDay(p.y, p.m, p.d, hour));
        expect.soft(Math.abs(angleDiff(lon, truth)) * 60,
          `Moon ${day.date} ${hour}h`).toBeLessThan(2.5);
      });
    }
  });

  it("confirms the Moon moves 11–16° a day — the reason date-only input is uncertain", () => {
    for (const day of golden.moon_days) {
      const arc = ((day.hourly[24] - day.hourly[0]) % 360 + 360) % 360;
      expect(arc).toBeGreaterThan(11);
      expect(arc).toBeLessThan(16);
    }
  });
});

describe("calendar handling", () => {
  it("round-trips Julian Day against the calendar", () => {
    for (const iso of ["1900-01-01", "1969-07-20", "2000-02-29", "2026-08-03", "2099-12-31"]) {
      const p = parseDate(iso)!;
      const back = fromJulianDay(julianDay(p.y, p.m, p.d, 12));
      expect(`${back.y}-${String(back.m).padStart(2, "0")}-${String(back.d).padStart(2, "0")}`).toBe(iso);
    }
  });

  it("rejects calendar-impossible dates instead of silently rolling them over", () => {
    // Date.UTC turns 2001-02-29 into 2001-03-01, so without an explicit round-trip check a mistyped
    // birthday would quietly chart the wrong day.
    expect(parseDate("2001-02-29")).toBeNull();
    expect(parseDate("2000-02-29")).not.toBeNull(); // 2000 IS a leap year
    expect(parseDate("2026-13-01")).toBeNull();
    expect(parseDate("2026-04-31")).toBeNull();
    expect(parseDate("not-a-date")).toBeNull();
    expect(parseDate("1700-01-01")).toBeNull(); // outside the verified range
  });

  it("crosses the Mesha Sankranti at the right date — the defining sidereal checkpoint", () => {
    // The Sun enters 0° sidereal Aries around 14 April, NOT at the March equinox. If the ayanamsa
    // were dropped or doubled this is the test that would notice.
    const before = siderealLongitude("Sun", julianDay(2026, 4, 13, 12));
    const after = siderealLongitude("Sun", julianDay(2026, 4, 15, 12));
    expect(before).toBeGreaterThan(355); // still late Pisces
    expect(after).toBeLessThan(5);       // now early Aries
  });
});
