import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { extname, join } from "node:path";
const DIST="/Users/arash/Studio/artamatch/dist";
const MIME={".html":"text/html",".js":"text/javascript",".css":"text/css",".map":"application/json"};
const server=createServer((req,res)=>{let p=decodeURIComponent(req.url.split("?")[0]).replace(/^\/artamatch/,"");if(p==="/"||p==="")p="/index.html";const f=join(DIST,p);if(!existsSync(f)){res.writeHead(404);return res.end("nf");}res.writeHead(200,{"Content-Type":MIME[extname(f)]||"application/octet-stream"});res.end(readFileSync(f));});
await new Promise(r=>server.listen(4401,r));
const b=await chromium.launch(); const page=await b.newPage({viewport:{width:1280,height:1000},deviceScaleFactor:2});
const OUT="/private/tmp/claude-501/-Users-arash-Studio-artaquest/e237389f-673e-4ad4-a047-ee9f3cdec7b3/scratchpad";
await page.goto("http://localhost:4401/artamatch/",{waitUntil:"networkidle"});
await page.locator(".rank-row").first().click();
await page.waitForSelector(".anatomy");
await page.locator(".anatomy").screenshot({path:OUT+"/anatomy.png"});
await page.locator(".hero").screenshot({path:OUT+"/hero.png"});
await page.locator(".ruler-wrap").screenshot({path:OUT+"/ruler.png"});
console.log("anatomy textContent:", JSON.stringify(await page.locator(".anatomy").textContent()));
console.log("ruler textContent:", JSON.stringify(await page.locator(".ruler").textContent()));
// focus rings
await page.goto("http://localhost:4401/artamatch/",{waitUntil:"networkidle"});
await page.locator("button.who").first().focus();
await page.locator(".panel").nth(3).screenshot({path:OUT+"/focus-who.png"});
await page.getByRole("button",{name:"Add to my list"}).focus();
await page.locator(".panel").first().screenshot({path:OUT+"/focus-add.png"});
await page.locator(".opt input").first().focus();
await page.locator(".panel").nth(2).screenshot({path:OUT+"/focus-opt.png"});
await b.close(); server.close();
